version: "3.3"

networks:
   default:
      external:
         name: syntheticnet

services:
  db:
    container_name: db
    hostname: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    volumes:
      - ./postgresql/db_schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./dbdata:/var/lib/postgresql/data:Z
    env_file:
      - ./postgresql/postgres.env
